#!/bin/bash

# Get the current user's home directory
USER_HOME=$HOME

# Step 1: Generate LLVM IR file
echo "Step 1: Generate LLVM IR file"

clang -g0 -O0 -Xclang -disable-O0-optnone -target armv7e-m -mcpu=cortex-m4 -mfloat-abi=soft -mthumb -S -emit-llvm -Wall -Wextra -o $HOME/CoSense/applications/newton/llvm-ir/MadgwickAHRS.ll $HOME/CoSense/applications/newton/llvm-ir/c-files/MadgwickAHRS.c

# Step 2: Use newton for optimization and quantization
echo "Step 2: Use newton for optimization and quantization"
cd $USER_HOME/CoSense/src/newton && ./newton-linux-EN --llvm-ir=$USER_HOME/CoSense/applications/newton/llvm-ir/MadgwickAHRS.ll --llvm-ir-liveness-check --llvm-ir-auto-quantization $USER_HOME/CoSense/applications/newton/sensors/test.nt

# Step 3: Convert generated bytecode file to LLVM IR file
echo "Step 3: Convert generated bytecode file to LLVM IR file"
#llvm-dis $USER_HOME/CoSense/applications/newton/llvm-ir/MadgwickAHRS_opt.bc -o $USER_HOME/CoSense/applications/newton/llvm-ir/MadgwickAHRS_opt.ll
cd $USER_HOME/CoSense/applications/newton/llvm-ir/&&
./replace.sh $USER_HOME/CoSense/applications/newton/llvm-ir/MadgwickAHRS_opt.ll

python3 replace.py

echo "Step 2: Optimize the generated LLVM IR file"


opt $USER_HOME/CoSense/applications/newton/llvm-ir/MadgwickAHRS_opt.ll  -S -o $USER_HOME/CoSense/applications/newton/llvm-ir/out.ll

echo "Step 3: Compile the optimized LLVM IR file to bitcode"

llvm-as $HOME/CoSense/applications/newton/llvm-ir/out.ll -o $HOME/CoSense/applications/newton/llvm-ir/out.bc

echo "Step 4: Compile the bitcode file to assembly"

llc -march=arm -mcpu=cortex-m4 -mattr=+thumb,+soft-float $HOME/CoSense/applications/newton/llvm-ir/out.bc -o $HOME/CoSense/applications/newton/llvm-ir/out.s

echo "Step 5: Compile the assembly file to object file"

#clang -c $HOME/CoSense/applications/newton/llvm-ir/out.s -o $HOME/CoSense/applications/newton/llvm-ir/out.o

clang -target armv7e-m -mcpu=cortex-m4 -mfloat-abi=soft -mthumb -c $HOME/CoSense/applications/newton/llvm-ir/out.s -o $HOME/CoSense/applications/newton/llvm-ir/out.o