#!/bin/bash

# Get the current user's home directory
USER_HOME=$HOME

FILE_PATH="$HOME/CoSense/applications/newton/llvm-ir/floating_point_operations_opt.ll"

 #Step 1: Generate LLVM IR file
echo "Step 1: Generate LLVM IR file"
clang -g0 -O0  -Xclang -disable-O0-optnone  -S -emit-llvm -Wall -Wextra  -o $HOME/CoSense/applications/newton/llvm-ir/floating_point_operations.ll $HOME/CoSense/applications/newton/llvm-ir/c-files/floating_point_operations.c

# Step 2: Use newton for optimization and quantization
echo "Step 2: Use newton for optimization and quantization"
cd $HOME/CoSense/src/newton && ./newton-linux-EN --llvm-ir=$HOME/CoSense/applications/newton/llvm-ir/floating_point_operations.ll --llvm-ir-liveness-check --llvm-ir-auto-quantization $HOME/CoSense/applications/newton/sensors/test.nt
#
# Step 3: Convert generated bytecode file to LLVM IR file
echo "Step 3: Convert generated bytecode file to LLVM IR file"
#llvm-dis $HOME/CoSense/applications/newton/llvm-ir/floating_point_operations_opt.bc -o $HOME/CoSense/applications/newton/llvm-ir/floating_point_operations_opt.ll
#cd $HOME/CoSense/applications/newton/llvm-ir/&&
#./replace.sh $HOME/CoSense/applications/newton/llvm-ir/floating_point_operations_opt.ll

#python3 replace.py


# Step 4: Optimize the generated LLVM IR file
echo "Step 4: Optimize the generated LLVM IR file"
#opt $HOME/CoSense/applications/newton/llvm-ir/floating_point_operations_output.ll   -S -o $HOME/CoSense/applications/newton/llvm-ir/out.ll